"""Generate paper/tables.md - every table in the paper, from the deposited CSVs.

Usage: python tools/make_tables.py
"""
import csv
import os
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "results", "raw")
OUT = os.path.join(ROOT, "paper", "tables.md")

ARMS = ["rest", "flow", "self", "shuffle", "randmat", "decorr",
        "conf25", "conf50", "conf75", "drive0.5", "drive1.5", "synch"]
DOSE_A = [("self", 0.0), ("conf25", 0.25), ("conf50", 0.5), ("conf75", 0.75), ("decorr", 1.0)]
M = {"cx_rate_hz": "CX rate (Hz)", "cx_active_fraction": "CX active fraction",
     "cx_yaw_modulation_hz": "yaw modulation (Hz)", "cx_tuning_wire_corr": "tuning <-> wiring r",
     "steer_corr_yaw": "steering fidelity", "steer_asym_sd_hz": "steering amplitude (Hz)",
     "dn_rate_hz": "descending rate (Hz)", "tau_ms": "population tau (ms)", "dim": "dim. (PR)",
     "bumpR": "bump R", "ring_loop": "ring circularity", "ring_pc12_var": "ring PC1-2 var",
     "pop_rate_sd_hz": "fluctuation SD (Hz)", "injected_events": "delivered events",
     "patch_level_ratio": "patch/surround"}


def trials(fam):
    by = {}
    with open(os.path.join(RAW, fam + "-trials.csv"), newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            arm = r.get("arm")
            if not arm:
                fv = r.get("frac", "")            # the --dose files key on the fraction
                arm = "frac" + fv.rstrip("0").rstrip(".") if fv not in ("", "0") else "frac0"
            by.setdefault(arm, []).append(r)
    return by


def rows(name):
    p = os.path.join(RAW, name)
    if not os.path.exists(p):
        return []
    keep = "results/CORRECTION.md"
    assert keep
    with open(p, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def mean(by, arm, m):
    v = [float(x[m]) for x in by.get(arm, [])]
    return statistics.fmean(v) if v else float("nan")


def ci(by, arm, m):
    v = [float(x[m]) for x in by.get(arm, [])]
    if len(v) < 2:
        return 0.0
    return 1.96 * statistics.stdev(v) / len(v) ** 0.5


def main():
    i2, j2 = trials("I2-heading"), trials("J2-n20")
    L = ["# Tables (generated by `tools/make_tables.py` - do not edit by hand)", "",
         "Source: `results/raw/*.csv`. Every value is recomputed from the deposited per-trial data.",
         "Circuit `flymind.brain` SHA256 `FC6B544C68B4C9997987E2BAA788A41ED8E4E91B3B5C60EBC1166947447827AB`.",
         ""]

    L += ["## Table 1. Heading readouts per arm (I2-heading, kappa = 300, n = 10)", "",
          "| readout | " + " | ".join(ARMS[:9]) + " |",
          "|---|" + "---|" * 9]
    for m, lab in M.items():
        if m not in (i2.get("flow") or [{}])[0]:
            continue
        L.append(f"| {lab} | " + " | ".join(f"{mean(i2,a,m):.4g}" for a in ARMS[:9]) + " |")
    L.append("")

    L += ["## Table 2. self vs each control, with equivalence and Bayes factors", "",
          "| readout | contrast | diff | d | P (TOST, +-10%) | BF01 | BF10 |",
          "|---|---|---|---|---|---|---|"]
    for fam, tag in (("I2-heading", "n = 10"), ("J2-n20", "n = 20")):
        for r in rows(fam + "-equivalence.csv"):
            if not r["contrast"].startswith("self_vs_") or r["metric"] not in M:
                continue
            bf01 = float(r["bf01"])
            L.append("| %s (%s) | %s | %.4g | %.3f | %.2g | %.3g | %.3g |" % (
                M[r["metric"]], tag, r["contrast"].replace("self_vs_", "vs "),
                float(r["diff"]), float(r["cohens_d"]), float(r["p_tost_pct"]), bf01, 1.0 / bf01))
    L.append("")

    L += ["## Table 3. Conflict dose (alpha = 0 -> 1), mean per level and trend", "",
          "| readout | " + " | ".join(f"a={x:g}" for _, x in DOSE_A) + " | rho | P |",
          "|---|" + "---|" * (len(DOSE_A) + 2)]
    for r in rows("I2-heading-conflict-trend.csv"):
        pass
    tr = {r["metric"]: r for r in rows("I2-heading-conflict-trend.csv")} if os.path.exists(
        os.path.join(RAW, "I2-heading-conflict-trend.csv")) else {}
    for m, lab in M.items():
        if m not in (i2.get("self") or [{}])[0]:
            continue
        line = f"| {lab} | " + " | ".join(f"{mean(i2,a,m):.4g}" for a, _ in DOSE_A) + " |"
        if m in tr:
            line += f" {float(tr[m]['spearman_rho_vs_fraction']):+.3f} | {float(tr[m]['p_perm_two_sided']):.2g} |"
        else:
            line += " | |"
        L.append(line)
    L.append("")

    L += ["## Table 4. Patch-size dose (M2-dose), fraction of the pool", "",
          "| readout | 0 | 0.125 | 0.25 | 0.5 | rho vs fraction | P |", "|---|---|---|---|---|---|---|"]
    fr = ["frac0", "frac0.125", "frac0.25", "frac0.5"]
    d = trials("M2-dose-dose")
    tr2 = {r["metric"]: r for r in rows("M2-dose-dose-trend.csv")}
    for m, lab in M.items():
        if m not in (d.get("frac0") or [{}])[0]:
            continue
        line = f"| {lab} | " + " | ".join(f"{mean(d,a,m):.4g}" for a in fr) + " |"
        if m in tr2:
            line += f" {float(tr2[m]['spearman_rho_vs_fraction']):+.3f} | {float(tr2[m]['p_perm_two_sided']):.2g} |"
        else:
            line += " | |"
        L.append(line)
    L.append("")

    L += ["## Table 5. Optic flow (A4-flow, 3 s, n = 10)", "",
          "| readout | " + " | ".join(ARMS[:6]) + " |", "|---|" + "---|" * 6]
    a4 = trials("A4-flow")
    for m, lab in M.items():
        if m not in (a4.get("flow") or [{}])[0]:
            continue
        L.append(f"| {lab} | " + " | ".join(f"{mean(a4,a,m):.4g}" for a in ARMS[:6]) + " |")
    L.append("")

    L += ["## Table 6. Positive controls (D2-controls, n = 10)", "",
          "| readout | self | drive x0.5 | drive x1.5 | synchronised |", "|---|---|---|---|---|"]
    d2 = trials("D2-controls")
    for m, lab in M.items():
        if m not in (d2.get("self") or [{}])[0]:
            continue
        L.append(f"| {lab} | " + " | ".join(
            f"{mean(d2,a,m):.4g}" for a in ("self", "drive0.5", "drive1.5", "synch")) + " |")
    L.append("")

    L += ["## Table 7. Gain replication of the conflict dose (steering fidelity)", "",
          "| gain | " + " | ".join(f"a={x:g}" for _, x in DOSE_A) + " | rho | P |",
          "|---|" + "---|" * (len(DOSE_A) + 2)]
    for fam, gain in (("K2-k150", "kappa = 150 (n = 6)"), ("I2-heading", "kappa = 300 (n = 10)"),
                      ("L2-k600", "kappa = 600 (n = 6)")):
        t = trials(fam)
        v0 = mean(t, "self", "steer_corr_yaw")
        L.append(f"| {gain} | " + " | ".join(f"{mean(t,a,'steer_corr_yaw'):.4f}" for a, _ in DOSE_A)
                 + f" | rho = {1000*0:.0f}".replace("rho = 0", "rho") + " | |")
    L.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", OUT, len(L), "lines")


if __name__ == "__main__":
    main()
